import type { Recipe, Material, Task, Note } from '../types';

export const MOCK_RECIPES: Recipe[] = [
  {
    id: 9001,
    num: 'V-A',
    name: '沉木供香（假）',
    fragCat: 'shrine',
    status: 'success',
    rating: 4,
    tags: ['供香', '沉水'],
    process: { tincture: false, ferment: false, wine: false, notes: '' },
    timeline: { makeDate: '2026-03-10', dryDays: 7, agingStart: '2026-03-20', agingNotes: '窖藏 30 天' },
    versions: [
      {
        label: '主版',
        totalWeight: 20,
        ingredients: [
          { cat: 'base', name: '沉香粉', amount: 10, unit: 'g' },
          { cat: 'base', name: '白檀粉', amount: 4, unit: 'g' },
          { cat: 'resin', name: '乳香', amount: 2, unit: 'g' },
          { cat: 'botanical', name: '丁香', amount: 1, unit: 'g' },
          { cat: 'binder', name: '楠木粉', amount: 3, unit: 'g' },
        ],
        notes: '前調偏甜木質，中後調有微微煙薰感',
        comments: [],
      },
    ],
    burnLog: [
      { date: '2026-03-22', front: '甜木、微煙', mid: '沉穩木質', tail: '淡淡樹脂', smoke: 'good', rating: 4, notes: '燃燒均勻，煙細直' },
    ],
    createdAt: '2026-03-10T00:00:00.000Z',
    updatedAt: '2026-03-22T00:00:00.000Z',
  },
  {
    id: 9002,
    num: 'V-B',
    name: '草本舒心（假）',
    fragCat: 'green',
    status: 'progress',
    rating: 0,
    tags: ['草本', '舒緩'],
    process: { tincture: true, ferment: false, wine: false, notes: '艾草酊劑浸泡中' },
    timeline: { makeDate: '2026-03-25', dryDays: 5, agingStart: '', agingNotes: '' },
    versions: [
      {
        label: '初版',
        totalWeight: 15,
        ingredients: [
          { cat: 'base', name: '柏木粉', amount: 6, unit: 'g' },
          { cat: 'botanical', name: '艾草', amount: 3, unit: 'g' },
          { cat: 'botanical', name: '薰衣草', amount: 2, unit: 'g' },
          { cat: 'tincture', name: '艾草酊劑', amount: 1.5, unit: 'g' },
          { cat: 'binder', name: '楠木粉', amount: 2.5, unit: 'g' },
        ],
        notes: '待酊劑製作完成再調整比例',
        comments: [],
      },
    ],
    burnLog: [],
    createdAt: '2026-03-25T00:00:00.000Z',
    updatedAt: '2026-03-25T00:00:00.000Z',
  },
  {
    id: 9003,
    num: 'V-C',
    name: '花果秘境（假）',
    fragCat: 'floral',
    status: 'pending',
    rating: 0,
    tags: ['花香', '果香'],
    process: { tincture: false, ferment: false, wine: true, notes: '' },
    timeline: { makeDate: '', dryDays: 5, agingStart: '', agingNotes: '' },
    versions: [
      {
        label: '草稿',
        totalWeight: 20,
        ingredients: [
          { cat: 'base', name: '白檀粉', amount: 8, unit: 'g' },
          { cat: 'botanical', name: '玫瑰花瓣', amount: 3, unit: 'g' },
          { cat: 'botanical', name: '桂花', amount: 2, unit: 'g' },
          { cat: 'resin', name: '安息香', amount: 2, unit: 'g' },
          { cat: 'binder', name: '楠木粉', amount: 5, unit: 'g' },
        ],
        notes: '待材料備齊後製作',
        comments: [],
      },
    ],
    burnLog: [],
    createdAt: '2026-03-28T00:00:00.000Z',
    updatedAt: '2026-03-28T00:00:00.000Z',
  },
  {
    id: 9004,
    num: 'V-D',
    name: '松脂山嵐（假）',
    fragCat: 'resin',
    status: 'fail',
    rating: 1,
    tags: ['松脂', '山野'],
    process: { tincture: false, ferment: false, wine: false, notes: '' },
    timeline: { makeDate: '2026-02-15', dryDays: 7, agingStart: '', agingNotes: '' },
    versions: [
      {
        label: '主版',
        totalWeight: 20,
        ingredients: [
          { cat: 'resin', name: '松脂', amount: 8, unit: 'g' },
          { cat: 'base', name: '松木粉', amount: 6, unit: 'g' },
          { cat: 'binder', name: '楠木粉', amount: 6, unit: 'g' },
        ],
        notes: '松脂比例過高，燃燒時噴火',
        comments: [],
      },
    ],
    burnLog: [
      { date: '2026-02-20', front: '強烈松脂', mid: '焦糊感', tail: '無', smoke: 'bad', rating: 1, notes: '松脂過多燃燒不穩定，需重新調整' },
    ],
    createdAt: '2026-02-15T00:00:00.000Z',
    updatedAt: '2026-02-20T00:00:00.000Z',
  },
];

export const MOCK_TASKS: Task[] = [
  {
    id: 'mock_t1',
    title: '艾草酊劑浸泡（假）',
    material: '艾草',
    recipeId: 9002,
    taskType: 'tincture',
    status: 'waiting',
    startDate: '2026-03-15',
    dueDate: '2026-04-12',
    completedDate: null,
    notes: '95% 酒精浸泡 28 天，每週搖晃',
    checkpoints: [],
    createdAt: '2026-03-15T00:00:00.000Z',
    updatedAt: '2026-03-15T00:00:00.000Z',
  },
  {
    id: 'mock_t2',
    title: '沉香粉烘乾處理（假）',
    material: '沉香粉',
    recipeId: null,
    taskType: 'dry',
    status: 'processing',
    startDate: '2026-03-27',
    dueDate: '2026-04-03',
    completedDate: null,
    notes: '低溫 45°C 烘乾，去除多餘水分',
    checkpoints: [],
    createdAt: '2026-03-27T00:00:00.000Z',
    updatedAt: '2026-03-27T00:00:00.000Z',
  },
  {
    id: 'mock_t3',
    title: '沉木供香 V-A 窖藏（假）',
    material: '',
    recipeId: 9001,
    taskType: 'cellar',
    status: 'waiting',
    startDate: '2026-03-20',
    dueDate: '2026-04-19',
    completedDate: null,
    notes: '密封陶甕，恆溫恆濕環境',
    checkpoints: [],
    createdAt: '2026-03-20T00:00:00.000Z',
    updatedAt: '2026-03-20T00:00:00.000Z',
  },
  {
    id: 'mock_t4',
    title: '花果秘境稱量配粉（假）',
    material: '',
    recipeId: 9003,
    taskType: 'weigh',
    status: 'ready',
    startDate: '2026-03-29',
    dueDate: null,
    completedDate: null,
    notes: '材料已備齊，待製作',
    checkpoints: [],
    createdAt: '2026-03-29T00:00:00.000Z',
    updatedAt: '2026-03-29T00:00:00.000Z',
  },
  {
    id: 'mock_t5',
    title: '松脂山嵐 V2 試燒（假）',
    material: '',
    recipeId: 9004,
    taskType: 'burn',
    status: 'ready',
    startDate: '2026-03-29',
    dueDate: null,
    completedDate: null,
    notes: '調整松脂比例後再次試燒',
    checkpoints: [],
    createdAt: '2026-03-29T00:00:00.000Z',
    updatedAt: '2026-03-29T00:00:00.000Z',
  },
];

export const MOCK_MATERIALS: Material[] = [
  { id: 'mock_m1', cat: 'base',      name: '沉香粉',   origin: '越南',   supplier: '大然香業', note: '惠安級，甜木香',         stock: { qty: 120, unit: 'g', note: '' } },
  { id: 'mock_m2', cat: 'base',      name: '白檀粉',   origin: '印度',   supplier: '大然香業', note: '老山白檀',              stock: { qty: 250, unit: 'g', note: '' } },
  { id: 'mock_m3', cat: 'base',      name: '柏木粉',   origin: '台灣',   supplier: '自採',    note: '扁柏，清涼感',           stock: { qty: 80,  unit: 'g', note: '快用完' } },
  { id: 'mock_m4', cat: 'botanical', name: '艾草',     origin: '台灣',   supplier: '農市',    note: '端午採收，乾燥',          stock: { qty: 45,  unit: 'g', note: '' } },
  { id: 'mock_m5', cat: 'botanical', name: '玫瑰花瓣', origin: '保加利亞', supplier: '進口商',  note: '精油含量高',             stock: { qty: 30,  unit: 'g', note: '庫存偏低' } },
  { id: 'mock_m6', cat: 'resin',     name: '乳香',     origin: '索馬利亞', supplier: '進口商',  note: 'Boswellia carterii',   stock: { qty: 150, unit: 'g', note: '' } },
  { id: 'mock_m7', cat: 'resin',     name: '安息香',   origin: '泰國',   supplier: '進口商',  note: '香草甜味',              stock: { qty: 60,  unit: 'g', note: '' } },
  { id: 'mock_m8', cat: 'tincture',  name: '艾草酊劑', origin: '自製',   supplier: '—',       note: '浸泡中，預計 4/12 完成', stock: { qty: 100, unit: 'ml', note: '浸泡中' } },
  { id: 'mock_m9', cat: 'binder',    name: '楠木粉',   origin: '台灣',   supplier: '大然香業', note: '黏性強，用量 15-20%',    stock: { qty: 500, unit: 'g', note: '' } },
];

export const MOCK_NOTES: Note[] = [
  {
    id: 'mock_n1',
    text: '今天試聞了沉木供香成品，前調甜而不膩，點燃約 3 分鐘後進入沉香本體香氣，燃燒均勻線香不會斷。整體評價不錯，可以考慮調整乳香比例再做一批。（假）',
    ts: Date.now() - 2 * 3600000,
    aiResult: undefined,
  },
  {
    id: 'mock_n2',
    text: '艾草酊劑觀察：顏色已轉為深綠褐色，香氣明顯。再等兩週應該可以過濾使用。（假）',
    ts: Date.now() - 26 * 3600000,
    aiResult: undefined,
  },
];
